language: c
sudo: false
dist: "trusty"
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="Adafruit ImageLoader Arduino Library"

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --install-library "Adafruit ST7735 and ST7789 Library","Adafruit HX8357 Library","Adafruit ILI9341","Adafruit GFX Library","Adafruit seesaw Library","Adafruit SSD1351 library","Adafruit SSD1331 OLED Driver Library for Arduino","Adafruit SPIFlash","SdFat - Adafruit Fork"

script:
   - build_main_platforms
   - build_cplay_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
